### ISSUE TITLE
Implementation for method "DatasetIterator_ImageText" cannot be found

### ISSUE THREAD

**Issue by 1503-firmansyah-indra** [stevejpapad/Visual-InCompatibility-Transformer#2]
When running the method `extract_visual_features` in file `FLIP.py`, method `DatasetIterator_ImageText` is called in line 562. However, this method has not been defined anywhere in the repo. Could you add the implementation for `DatasetIterator_ImageText`?

**Comment by stevejpapad** [comment]
Thanks for raising this issue. The function should have been `DatasetIterator_FLIP` instead of `DatasetIterator_ImageText`. I have now altered `FLIP.py`. Please let me know if you face any other problem.

**Comment by 1503-firmansyah-indra** [comment]
This is now fixed, thank you.
